[build]
  command = "npm run build"
  publish="/build"
  base = ""
[[redirects]]
  force = true
  from = "/api/*"
  status = 200
  to = "/.netlify/functions/api/:splat"
[functions]
  external_node_modules = ["express"]
  node_bundler = "esbuild"